version: '3.8'

services:
  app:
    container_name: webapp
    image: mendhak/http-https-echo:26
    networks:
      - my_network
    ports:
      - "8080:8080"

  nginx-proxy:
    container_name: proxy
    image: nginx-demo-proxy
    build:
      context: ./proxy
    networks:
      - my_network
    ports:
      - "5001:80"

networks:
  my_network:
