version: '3.8'

x-project_name: demo-nginx-proxy

services:
  app:
    container_name: webapp
    image: nginx-demo-app
    build:
      context: ./app
    networks:
      - my_network

  nginx-proxy:
    container_name: proxy
    image: nginx-demo-proxy
    build:
      context: ./proxy
    networks:
      - my_network
    ports:
      - "5001:80"

networks:
  my_network:
